-- +goose Up
-- +goose StatementBegin

-- Baseline schema.
--
-- This single migration replaces the 139-file historical chain that preceded
-- it. Those files encoded the schema's development history: renumbered
-- versions, 16 burned version numbers, and per-migration data repairs for
-- databases that only ever existed on developer machines and fast-moving
-- Nightly builds. No supported install is carried forward from that chain, so
-- the baseline is the current table state and every later change is a new
-- version appended after this one.
--
-- Frozen: do not edit this file to change the schema. Add a new migration.


CREATE TABLE telemetry_event (
    id TEXT PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    name TEXT NOT NULL,
    source TEXT NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('debug', 'info', 'warn', 'error')),
    project_id TEXT,
    session_id TEXT,
    request_id TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL
);

CREATE TABLE "projects" (
    id              TEXT PRIMARY KEY,
    path            TEXT NOT NULL,
    repo_origin_url TEXT NOT NULL DEFAULT '',
    display_name    TEXT NOT NULL DEFAULT '',
    registered_at   TIMESTAMP NOT NULL,
    archived_at     TIMESTAMP,
    config          TEXT,
    kind            TEXT NOT NULL DEFAULT 'single_repo'
        CHECK (kind IN ('single_repo', 'workspace', 'scratch'))
);

CREATE TABLE sessions (
    id                      TEXT PRIMARY KEY,
    project_id              TEXT REFERENCES projects (id),
    num                     INTEGER NOT NULL,
    issue_id                TEXT NOT NULL DEFAULT '',
    kind                    TEXT NOT NULL DEFAULT 'worker'
        CHECK (kind IN ('worker', 'manager')),
    harness                 TEXT NOT NULL DEFAULT ''
        CHECK (harness IN ('', 'codex', 'aider', 'opencode', 'grok', 'droid', 'amp', 'agy', 'crush', 'cursor', 'qwen', 'copilot', 'goose', 'auggie', 'continue', 'devin', 'cline', 'kimi', 'muse', 'kiro', 'kilocode', 'vibe', 'pi', 'kimchi', 'prime-agent', 'autohand', 'omp', 'fake')),

    activity_state          TEXT NOT NULL DEFAULT 'idle'
        CHECK (activity_state IN ('active', 'idle', 'waiting_input', 'blocked', 'exited')),
    activity_last_at        TIMESTAMP NOT NULL,
    is_terminated           BOOLEAN NOT NULL DEFAULT FALSE,

    branch                  TEXT NOT NULL DEFAULT '',
    workspace_path          TEXT NOT NULL DEFAULT '',
    runtime_handle_id       TEXT NOT NULL DEFAULT '',
    agent_session_id        TEXT NOT NULL DEFAULT '',
    prompt                  TEXT NOT NULL DEFAULT '',

    created_at              TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP NOT NULL, display_name TEXT NOT NULL DEFAULT '', first_signal_at TIMESTAMP, preview_url TEXT NOT NULL DEFAULT '', preview_revision INTEGER NOT NULL DEFAULT 0, cleanup_generation INTEGER NOT NULL DEFAULT 0, runtime_launch_id TEXT NOT NULL DEFAULT '', workspace_repo_path TEXT NOT NULL DEFAULT '', terminate_on_pr_merge BOOLEAN NOT NULL DEFAULT FALSE, diff_base_sha TEXT NOT NULL DEFAULT '', diff_base_ref TEXT NOT NULL DEFAULT '', reviewer_harness TEXT NOT NULL DEFAULT '', is_pinned BOOLEAN NOT NULL DEFAULT 0, pinned_at DATETIME, session_mode TEXT NOT NULL DEFAULT 'tui', provider_conversation_id TEXT NOT NULL DEFAULT '', controller_generation TEXT NOT NULL DEFAULT '', browser_capability_verifier TEXT NOT NULL DEFAULT '', auto_inject_review BOOLEAN NOT NULL DEFAULT TRUE, latest_user_prompt TEXT NOT NULL DEFAULT '', latest_assistant_update TEXT NOT NULL DEFAULT '', native_transcript_path TEXT NOT NULL DEFAULT '', auto_inject_ci BOOLEAN NOT NULL DEFAULT TRUE, auto_review_enabled INTEGER NOT NULL DEFAULT 0, agent_session_id_launch_id TEXT NOT NULL DEFAULT '', model TEXT NOT NULL DEFAULT '', latest_user_prompt_at TIMESTAMP, reviewer_agent_config TEXT NOT NULL DEFAULT '', session_permissions TEXT NOT NULL DEFAULT '', conversation_checkpoint_state TEXT NOT NULL DEFAULT 'legacy'
    CHECK (conversation_checkpoint_state IN ('legacy', 'empty', 'coordination', 'prompt', 'complete')), conversation_checkpoint_generation TEXT NOT NULL DEFAULT '', conversation_checkpoint_native_id TEXT NOT NULL DEFAULT '', conversation_checkpoint_unsettled BOOLEAN NOT NULL DEFAULT 0, conversation_checkpoint_turn_id TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 0, native_checkpoint_evidence TEXT NOT NULL DEFAULT '', latest_assistant_update_at TIMESTAMP, native_identity_observed_at TIMESTAMP, workflow_mode TEXT NOT NULL DEFAULT 'planning', review_locked BOOLEAN NOT NULL DEFAULT FALSE,

    CHECK ((kind = 'manager' AND workflow_mode IN ('planning', 'manager')) OR (kind = 'worker' AND workflow_mode IN ('planning', 'building'))), UNIQUE (project_id, num)
);

CREATE TABLE pr (
    url             TEXT PRIMARY KEY,
    session_id      TEXT NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    number          INTEGER NOT NULL DEFAULT 0,
    pr_state        TEXT NOT NULL DEFAULT 'open'
        CHECK (pr_state IN ('draft', 'open', 'merged', 'closed')),
    review_decision TEXT NOT NULL DEFAULT 'none'
        CHECK (review_decision IN ('none', 'approved', 'changes_requested', 'review_required')),
    ci_state        TEXT NOT NULL DEFAULT 'unknown'
        CHECK (ci_state IN ('unknown', 'pending', 'passing', 'failing')),
    mergeability    TEXT NOT NULL DEFAULT 'unknown'
        CHECK (mergeability IN ('unknown', 'mergeable', 'conflicting', 'blocked', 'unstable')),
    updated_at      TIMESTAMP NOT NULL
, provider TEXT NOT NULL DEFAULT '', host TEXT NOT NULL DEFAULT '', repo TEXT NOT NULL DEFAULT '', source_branch TEXT NOT NULL DEFAULT '', target_branch TEXT NOT NULL DEFAULT '', head_sha TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', additions INTEGER NOT NULL DEFAULT 0, deletions INTEGER NOT NULL DEFAULT 0, changed_files INTEGER NOT NULL DEFAULT 0, author TEXT NOT NULL DEFAULT '', base_sha TEXT NOT NULL DEFAULT '', merge_commit_sha TEXT NOT NULL DEFAULT '', is_draft INTEGER NOT NULL DEFAULT 0, is_merged INTEGER NOT NULL DEFAULT 0, is_closed INTEGER NOT NULL DEFAULT 0, provider_state TEXT NOT NULL DEFAULT '', provider_mergeable TEXT NOT NULL DEFAULT '', provider_merge_state_status TEXT NOT NULL DEFAULT '', html_url TEXT NOT NULL DEFAULT '', created_at_provider TIMESTAMP, updated_at_provider TIMESTAMP, merged_at_provider TIMESTAMP, closed_at_provider TIMESTAMP, metadata_hash TEXT NOT NULL DEFAULT '', ci_hash TEXT NOT NULL DEFAULT '', review_hash TEXT NOT NULL DEFAULT '', observed_at TIMESTAMP, ci_observed_at TIMESTAMP, review_observed_at TIMESTAMP, last_nudge_signature TEXT NOT NULL DEFAULT '', state_changed_at TIMESTAMP, auto_inject_ci BOOLEAN NOT NULL DEFAULT TRUE, provider_id TEXT NOT NULL DEFAULT '', author_avatar_url TEXT NOT NULL DEFAULT '', review_partial BOOLEAN NOT NULL DEFAULT TRUE);

CREATE TABLE pr_checks (
    pr_url      TEXT NOT NULL REFERENCES pr (url) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    commit_hash TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'unknown'
        CHECK (status IN ('unknown', 'queued', 'in_progress', 'passed', 'failed', 'skipped', 'cancelled')),
    url         TEXT NOT NULL DEFAULT '',
    log_tail    TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMP NOT NULL, conclusion TEXT NOT NULL DEFAULT '', details TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (pr_url, name, commit_hash)
);

CREATE TABLE pr_comment (
    pr_url     TEXT NOT NULL REFERENCES pr (url) ON DELETE CASCADE,
    comment_id TEXT NOT NULL,
    author     TEXT NOT NULL DEFAULT '',
    file       TEXT NOT NULL DEFAULT '',
    line       INTEGER NOT NULL DEFAULT 0,
    body       TEXT NOT NULL DEFAULT '',
    resolved   INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL, thread_id TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '', is_bot INTEGER NOT NULL DEFAULT 0, auto_inject_review BOOLEAN NOT NULL DEFAULT TRUE, review_id TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (pr_url, comment_id)
);

CREATE TABLE pr_review_threads (
    pr_url        TEXT NOT NULL REFERENCES pr (url) ON DELETE CASCADE,
    thread_id     TEXT NOT NULL,
    path          TEXT NOT NULL DEFAULT '',
    line          INTEGER NOT NULL DEFAULT 0,
    resolved      INTEGER NOT NULL DEFAULT 0,
    is_bot        INTEGER NOT NULL DEFAULT 0,
    semantic_hash TEXT NOT NULL DEFAULT '',
    updated_at    TIMESTAMP NOT NULL,
    PRIMARY KEY (pr_url, thread_id)
);

CREATE TABLE workspace_repos (
    project_id      TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    relative_path   TEXT NOT NULL,
    repo_origin_url TEXT NOT NULL DEFAULT '',
    registered_at   TIMESTAMP NOT NULL, default_branch TEXT NOT NULL DEFAULT '', git_status TEXT NOT NULL DEFAULT 'ready'
    CHECK (git_status IN ('ready', 'needs_init')),
    PRIMARY KEY (project_id, name),
    UNIQUE (project_id, relative_path)
);

CREATE TABLE session_worktrees (
    session_id     TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    repo_name      TEXT NOT NULL,
    branch         TEXT NOT NULL,
    base_sha       TEXT NOT NULL,
    worktree_path  TEXT NOT NULL,
    preserved_ref  TEXT NOT NULL DEFAULT '',
    state          TEXT NOT NULL DEFAULT 'active'
        CHECK (state IN ('active', 'removed', 'retry_remove', 'unavailable', 'stray_moved')), base_ref TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (session_id, repo_name)
);

CREATE TABLE notifications (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    pr_url TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL CHECK (
        type IN (
            'needs_input',
            'ready_to_merge',
            'pr_merged',
            'pr_closed_unmerged'
        )
    ),
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'unread' CHECK (status IN ('read', 'unread')),
    created_at TIMESTAMP NOT NULL
, resolved_at TIMESTAMP);

CREATE TABLE pr_reviews (
    pr_url       TEXT NOT NULL REFERENCES pr (url) ON DELETE CASCADE,
    review_id    TEXT NOT NULL,
    author       TEXT NOT NULL DEFAULT '',
    state        TEXT NOT NULL DEFAULT 'none'
        CHECK (state IN ('none', 'approved', 'changes_requested', 'review_required')),
    url          TEXT NOT NULL DEFAULT '',
    is_bot       INTEGER NOT NULL DEFAULT 0,
    submitted_at TIMESTAMP NOT NULL, body TEXT NOT NULL DEFAULT '', auto_inject_review BOOLEAN NOT NULL DEFAULT TRUE, target_sha TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (pr_url, review_id)
);

CREATE TABLE shell_terminals (
    handle_id   TEXT PRIMARY KEY,
    project_id  TEXT REFERENCES projects(id) ON DELETE CASCADE,
    working_dir TEXT NOT NULL,
    title       TEXT NOT NULL DEFAULT '',
    app_run_id  TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
, session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE, transient BOOLEAN NOT NULL DEFAULT FALSE);

CREATE TABLE session_cleanup_facts (
    session_id            TEXT NOT NULL PRIMARY KEY REFERENCES sessions (id) ON DELETE CASCADE,
    session_generation    INTEGER NOT NULL DEFAULT 0,
    runtime_released_at   TIMESTAMP,
    workspace_disposition TEXT NOT NULL DEFAULT 'pending'
        CHECK (workspace_disposition IN ('pending', 'removed', 'preserved_dirty', 'failed', 'not_applicable')),
    attempt_count         INTEGER NOT NULL DEFAULT 0,
    last_attempt_at       TIMESTAMP,
    next_attempt_at       TIMESTAMP,
    failure_code          TEXT NOT NULL DEFAULT ''
);

CREATE TABLE agent_model_catalog (
    agent_id TEXT NOT NULL,
    project_id TEXT NOT NULL DEFAULT '',
    binary_version TEXT NOT NULL DEFAULT '',
    catalog_json TEXT NOT NULL,
    source TEXT NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    PRIMARY KEY (agent_id, project_id)
);

CREATE TABLE conversations (
    id              TEXT PRIMARY KEY,
    scope           TEXT NOT NULL CHECK (scope IN ('session', 'project')),
	project_id      TEXT REFERENCES projects(id) ON DELETE CASCADE,
	session_id      TEXT REFERENCES sessions(id) ON DELETE CASCADE,
	-- The controller currently responsible for the narrative. For workers this
	-- equals session_id. For project-scoped orchestrators it is rebound whenever
	-- AO creates a clean replacement, while session_id remains NULL by scope.
	current_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    latest_sequence INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL, model TEXT, reasoning_effort TEXT, approval_mode TEXT, compacted_at TIMESTAMP, context_used INTEGER, context_window INTEGER, usage_input_tokens INTEGER, usage_output_tokens INTEGER, usage_cached_tokens INTEGER, usage_total_tokens INTEGER, rate_limit_primary_percent REAL, rate_limit_secondary_percent REAL, rate_limit_primary_resets_in INTEGER, rate_limit_secondary_resets_in INTEGER, rate_limit_plan TEXT, provider_title TEXT NOT NULL DEFAULT '', applied_title TEXT NOT NULL DEFAULT '', model_reroute_json TEXT, account_json TEXT, thread_state_json TEXT, mcp_servers_json TEXT, usage_cost REAL, usage_currency TEXT, active_branch_id TEXT NOT NULL DEFAULT '', opencode_mode TEXT NOT NULL DEFAULT '',
    -- One conversation per session, and one per project for the orchestrator.
    CHECK ((scope = 'session' AND session_id IS NOT NULL)
        OR (scope = 'project' AND session_id IS NULL))
);

CREATE TABLE conversation_provider_events (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id    TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    session_id         TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    provider_event_id  TEXT NOT NULL DEFAULT '',
    method             TEXT NOT NULL,
    payload_json       TEXT NOT NULL,
    received_at        TIMESTAMP NOT NULL
, branch_id TEXT NOT NULL DEFAULT '');

CREATE TABLE app_settings (
    id                   INTEGER PRIMARY KEY CHECK (id = 1),
    -- Defaults to 'tui' so an upgrade changes nobody's workflow. Chat is only
    -- ever chosen deliberately.
    default_session_mode TEXT NOT NULL DEFAULT 'tui'
        CHECK (default_session_mode IN ('chat', 'tui')),
    updated_at           TIMESTAMP NOT NULL
, cloud_offering INTEGER NOT NULL DEFAULT 0
        CHECK (cloud_offering IN (0, 1)));

-- app_settings is a structural singleton (CHECK (id = 1)), seeded at
-- migration time so every read is a plain SELECT.
INSERT INTO app_settings (id, default_session_mode, updated_at)
VALUES (1, 'chat', CURRENT_TIMESTAMP);

CREATE TABLE session_interface_transitions (
    id                       TEXT PRIMARY KEY,
    session_id               TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    source_mode              TEXT NOT NULL CHECK (source_mode IN ('chat', 'tui')),
    target_mode              TEXT NOT NULL CHECK (target_mode IN ('chat', 'tui')),
    policy                   TEXT NOT NULL CHECK (policy IN ('drain', 'interrupt')),
    phase                    TEXT NOT NULL CHECK (phase IN (
        'requested', 'preflighting', 'draining', 'source_stopping',
        'source_stopped', 'target_starting', 'activating',
        'completed', 'failed', 'cancelled', 'recovery_required'
    )),
    native_conversation_id   TEXT NOT NULL DEFAULT '',
    error_code               TEXT NOT NULL DEFAULT '',
    error_detail             TEXT NOT NULL DEFAULT '',
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL,
    completed_at             TIMESTAMP, notice_acknowledged_at TIMESTAMP, history_policy TEXT NOT NULL DEFAULT 'strict'
    CHECK (history_policy IN ('strict', 'provider_history')),
    CHECK (source_mode <> target_mode)
);

CREATE TABLE session_interface_transition_messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    transition_id   TEXT NOT NULL REFERENCES session_interface_transitions(id) ON DELETE CASCADE,
    message         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    delivered_at    TIMESTAMP
, client_message_id TEXT NOT NULL DEFAULT '');

CREATE TABLE "review" (
    id                 TEXT PRIMARY KEY,
    session_id         TEXT NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    project_id         TEXT NOT NULL REFERENCES projects (id),
    harness            TEXT NOT NULL,
    pr_url             TEXT NOT NULL DEFAULT '',
    reviewer_handle_id TEXT NOT NULL DEFAULT '',
    agent_session_id   TEXT NOT NULL DEFAULT '',
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NOT NULL, reviewer_activity_state TEXT NOT NULL DEFAULT '', reviewer_launch_id TEXT NOT NULL DEFAULT '',
    UNIQUE(session_id, harness)
);

CREATE TABLE review_run (
    id          TEXT PRIMARY KEY,
    review_id   TEXT NOT NULL REFERENCES review (id) ON DELETE CASCADE,
    session_id  TEXT NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    harness     TEXT NOT NULL,
    pr_url      TEXT NOT NULL DEFAULT '',
    -- the commit the pass reviewed; lets a repeat trigger for the same head
    -- short-circuit to the existing run.
    target_sha  TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'running',
    verdict     TEXT NOT NULL DEFAULT '',
    body        TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMP NOT NULL
, github_review_id TEXT NOT NULL DEFAULT '', delivered_at TIMESTAMP, batch_id TEXT NOT NULL DEFAULT '', auto_inject_review BOOLEAN NOT NULL DEFAULT TRUE, trigger_source TEXT NOT NULL DEFAULT 'manual');

CREATE TABLE pr_url_alias (
    alias_url     TEXT PRIMARY KEY,
    canonical_url TEXT NOT NULL REFERENCES pr(url) ON DELETE CASCADE,
    CHECK (alias_url != canonical_url)
);

CREATE TABLE "change_log" (
    seq        INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT REFERENCES projects (id),
    session_id TEXT REFERENCES sessions (id),
    event_type TEXT NOT NULL
        CHECK (event_type IN (
            'session_created',
            'session_updated',
            'pr_created',
            'pr_updated',
            'pr_check_recorded',
            'pr_session_changed',
            'pr_review_thread_added',
            'pr_review_thread_resolved',
            'review_run_created',
            'review_run_updated'
        )),
    payload    TEXT NOT NULL CHECK (json_valid(payload)),
    created_at TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE agent_install_jobs (
    target               TEXT PRIMARY KEY,
    status               TEXT NOT NULL CHECK (status IN ('installing', 'verifying', 'succeeded', 'failed', 'unsupported', 'interrupted')),
    method               TEXT NOT NULL DEFAULT '',
    command              TEXT NOT NULL DEFAULT '',
    expected_destination TEXT NOT NULL DEFAULT '',
    output               TEXT NOT NULL DEFAULT '',
    error                TEXT NOT NULL DEFAULT '',
    started_at           TIMESTAMP NOT NULL,
    finished_at          TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL
);

CREATE TABLE conversation_queued_edit_deliveries (
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    client_message_id TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (conversation_id, client_message_id)
);

CREATE TABLE conversation_edit_deliveries (
    conversation_id    TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    client_message_id  TEXT NOT NULL,
    request_json       TEXT NOT NULL,
    state              TEXT NOT NULL CHECK (state IN ('reserved', 'accepted', 'rejected')),
    source_branch_id   TEXT NOT NULL DEFAULT '',
    active_branch_id   TEXT NOT NULL DEFAULT '',
    turn_id            TEXT NOT NULL DEFAULT '',
    handled_by_session_id TEXT NOT NULL DEFAULT '',
    provider_turn_id   TEXT NOT NULL DEFAULT '',
    turn_state         TEXT NOT NULL DEFAULT '',
    turn_requested_at  TIMESTAMP,
    rejection_kind     TEXT NOT NULL DEFAULT '',
    rejection_message  TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMP NOT NULL,
    settled_at          TIMESTAMP, provider_work_started INTEGER NOT NULL DEFAULT 1 CHECK (provider_work_started IN (0, 1)),
    PRIMARY KEY (conversation_id, client_message_id)
);

CREATE TABLE conversation_steer_deliveries (
    conversation_id    TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    client_message_id  TEXT NOT NULL,
    request_json       TEXT NOT NULL,
    state              TEXT NOT NULL CHECK (state IN ('reserved', 'accepted', 'rejected')),
    provider_turn_id   TEXT NOT NULL DEFAULT '',
    activity_id        TEXT NOT NULL DEFAULT '',
    rejection_kind     TEXT NOT NULL DEFAULT '',
    rejection_message  TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMP NOT NULL,
    settled_at          TIMESTAMP,
    PRIMARY KEY (conversation_id, client_message_id)
);

CREATE TABLE "codex_account_switches" (
    id TEXT PRIMARY KEY,
    source_account_id TEXT NOT NULL,
    target_account_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    phase TEXT NOT NULL CHECK (phase IN (
        'requested', 'checkpointing_source', 'activating_target',
        'recovery_required', 'completed', 'failed'
    )),
    failure_code TEXT NOT NULL DEFAULT '',
    credentials_committed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    source_kind TEXT NOT NULL DEFAULT 'managed'
        CHECK (source_kind IN ('managed', 'device', 'none'))
);

CREATE TABLE "usage_bindings" (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id         TEXT NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    harness            TEXT NOT NULL CHECK (harness IN ('claude-code', 'codex', 'kimi', 'opencode')),
    native_root_id     TEXT NOT NULL CHECK (trim(native_root_id) <> ''),
    initial_model_id   TEXT NOT NULL DEFAULT '',
    state              TEXT NOT NULL CHECK (state IN ('discovering', 'active', 'finalizing', 'complete', 'partial')),
    last_error_code    TEXT NOT NULL DEFAULT '',
    updated_at         TIMESTAMP NOT NULL,
    provider_hint      TEXT NOT NULL DEFAULT '',
    UNIQUE (session_id, harness, native_root_id)
);

CREATE TABLE "usage_sources" (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    binding_id          INTEGER NOT NULL REFERENCES usage_bindings (id) ON DELETE CASCADE,
    kind                TEXT NOT NULL CHECK (kind IN ('claude_main', 'claude_subagent', 'codex_rollout', 'kimi_wire')),
    native_session_id   TEXT NOT NULL DEFAULT '',
    subagent_id         TEXT NOT NULL DEFAULT '',
    artifact_path       TEXT NOT NULL CHECK (trim(artifact_path) <> ''),
    file_identity       TEXT NOT NULL DEFAULT '',
    generation          INTEGER NOT NULL DEFAULT 0 CHECK (generation >= 0),
    byte_offset         INTEGER NOT NULL DEFAULT 0 CHECK (byte_offset >= 0),
    parser_state_json   TEXT NOT NULL DEFAULT '{}',
    state               TEXT NOT NULL CHECK (state IN ('pending', 'active', 'complete', 'error')),
    failure_count       INTEGER NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
    anomaly_count       INTEGER NOT NULL DEFAULT 0 CHECK (anomaly_count >= 0),
    next_retry_at       TIMESTAMP,
    last_error_code     TEXT NOT NULL DEFAULT '',
    updated_at          TIMESTAMP NOT NULL,
    UNIQUE (binding_id, artifact_path, generation)
);

CREATE TABLE "model_usage_events" (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    binding_id                  INTEGER NOT NULL REFERENCES usage_bindings (id) ON DELETE CASCADE,
    usage_source_id             INTEGER NOT NULL REFERENCES usage_sources (id) ON DELETE CASCADE,
    provider_id                 TEXT NOT NULL CHECK (provider_id IN ('openai', 'anthropic')),
    billing_provider_id         TEXT CHECK (billing_provider_id IS NULL OR trim(billing_provider_id) <> ''),
    model_id                    TEXT NOT NULL CHECK (trim(model_id) <> ''),
    usage_measurement_kind      TEXT NOT NULL
        CHECK (usage_measurement_kind IN ('native_reported', 'open_agents_estimated', 'mixed', 'unknown')),
    input_tokens                INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
    cached_input_tokens         INTEGER CHECK (cached_input_tokens IS NULL OR cached_input_tokens >= 0),
    uncached_input_tokens       INTEGER CHECK (uncached_input_tokens IS NULL OR uncached_input_tokens >= 0),
    output_tokens               INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
    provider_usage_json         TEXT
        CHECK (provider_usage_json IS NULL
               OR (json_valid(provider_usage_json) AND json_type(provider_usage_json, '$') = 'object')),
    source_event_key            TEXT NOT NULL CHECK (trim(source_event_key) <> ''),
    created_at                  TIMESTAMP,
    input_cost_nanos            INTEGER CHECK (input_cost_nanos IS NULL OR input_cost_nanos >= 0),
    cached_input_cost_nanos     INTEGER CHECK (cached_input_cost_nanos IS NULL OR cached_input_cost_nanos >= 0),
    output_cost_nanos           INTEGER CHECK (output_cost_nanos IS NULL OR output_cost_nanos >= 0),
    estimated_cost_nanos        INTEGER CHECK (estimated_cost_nanos IS NULL OR estimated_cost_nanos >= 0),
    pricing_version             TEXT NOT NULL DEFAULT '',
    billing_provider_source     TEXT CHECK (billing_provider_source IS NULL
                                             OR billing_provider_source IN ('observed', 'inferred')),
    UNIQUE (binding_id, source_event_key),
    CHECK (input_tokens IS NULL OR cached_input_tokens IS NULL OR uncached_input_tokens IS NULL
           OR input_tokens = cached_input_tokens + uncached_input_tokens)
);

CREATE TABLE retired_session_nums (
    project_id TEXT NOT NULL,
    num        INTEGER NOT NULL,
    retired_at TIMESTAMP NOT NULL,
    PRIMARY KEY (project_id, num)
);

CREATE TABLE "conversation_turns" (
    id                     TEXT PRIMARY KEY,
    conversation_id        TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    -- The one change: a retired session detaches its turns instead of taking
    -- them with it. Turns that keep an owner are unchanged.
    handled_by_session_id  TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    provider_turn_id       TEXT NOT NULL DEFAULT '',
    controller_generation  TEXT NOT NULL DEFAULT '',
    state                  TEXT NOT NULL CHECK (state IN ('queued', 'running', 'completed', 'recovered', 'interrupted', 'failed', 'cancelled')),
    error_message          TEXT NOT NULL DEFAULT '',
    requested_at           TIMESTAMP NOT NULL,
    started_at             TIMESTAMP,
    completed_at           TIMESTAMP,
    diff_json              TEXT NOT NULL DEFAULT '',
    rolled_back_at         TIMESTAMP,
    plan_json              TEXT NOT NULL DEFAULT '',
    branch_id              TEXT NOT NULL DEFAULT '',
    promotion_started_at   TIMESTAMP,
    promoted_to_turn_id    TEXT REFERENCES "conversation_turns"(id) ON DELETE SET NULL,
    retry_of_turn_id       TEXT REFERENCES "conversation_turns"(id) ON DELETE RESTRICT
);

CREATE TABLE conversation_messages (
    id                TEXT PRIMARY KEY,
    conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    turn_id           TEXT REFERENCES conversation_turns(id) ON DELETE SET NULL,
    sequence          INTEGER NOT NULL,
    revision          INTEGER NOT NULL DEFAULT 0,
    role              TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    -- origin is structural. Worker/automation identity is never inferred from a
    -- text prefix.
    origin            TEXT NOT NULL CHECK (origin IN ('human', 'automation', 'daemon', 'provider')),
    text              TEXT NOT NULL DEFAULT '',
    streaming          INTEGER NOT NULL DEFAULT 0,
    provider_item_id  TEXT NOT NULL DEFAULT '',
    client_message_id TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL, delivery_content_json TEXT NOT NULL DEFAULT '', branch_id TEXT NOT NULL DEFAULT '',
    UNIQUE (conversation_id, sequence)
);

CREATE TABLE "conversation_branches" (
    id                       TEXT PRIMARY KEY,
    conversation_id          TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    session_id               TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    provider_conversation_id TEXT NOT NULL DEFAULT '',
    parent_branch_id         TEXT REFERENCES "conversation_branches"(id) ON DELETE RESTRICT,
    fork_after_turn_id       TEXT REFERENCES conversation_turns(id) ON DELETE RESTRICT,
    replaced_turn_id         TEXT REFERENCES conversation_turns(id) ON DELETE RESTRICT,
    replacement_turn_id      TEXT REFERENCES conversation_turns(id) ON DELETE SET NULL,
    fork_after_sequence      INTEGER NOT NULL DEFAULT 0,
    created_at               TIMESTAMP NOT NULL
, strategy TEXT NOT NULL DEFAULT 'native', replay_cutoff_sequence INTEGER NOT NULL DEFAULT 0, replay_truncated INTEGER NOT NULL DEFAULT 0, provider_scope_id TEXT NOT NULL DEFAULT '', provider_ids_scoped INTEGER NOT NULL DEFAULT 0 CHECK (provider_ids_scoped IN (0, 1)));

CREATE TABLE "conversation_activities" (
    id                TEXT PRIMARY KEY,
    conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    turn_id           TEXT REFERENCES conversation_turns(id) ON DELETE SET NULL,
    sequence          INTEGER NOT NULL,
    revision          INTEGER NOT NULL DEFAULT 0,
    kind              TEXT NOT NULL CHECK (kind IN ('command', 'file_change', 'plan', 'reasoning', 'approval', 'usage', 'error', 'system', 'mcp_tool', 'auto_review', 'user_input')),
    status            TEXT NOT NULL CHECK (status IN ('running', 'completed', 'recovered', 'failed', 'cancelled', 'pending', 'resolved')),
    summary           TEXT NOT NULL DEFAULT '',
    detail_json       TEXT NOT NULL DEFAULT '',
    request_id        TEXT NOT NULL DEFAULT '',
    provider_item_id  TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    command_output    TEXT NOT NULL DEFAULT '',
    command_output_truncated INTEGER NOT NULL DEFAULT 0,
    streamed_text     TEXT NOT NULL DEFAULT '',
    streamed_text_truncated  INTEGER NOT NULL DEFAULT 0,
    branch_id         TEXT NOT NULL DEFAULT '',
    UNIQUE (conversation_id, sequence)
);

CREATE INDEX idx_sessions_project ON sessions (project_id);

CREATE INDEX idx_pr_session ON pr (session_id);

CREATE INDEX idx_pr_checks_lookup ON pr_checks (pr_url, name, created_at);

CREATE INDEX idx_pr_review_threads_lookup ON pr_review_threads (pr_url, updated_at);

CREATE INDEX idx_session_worktrees_session ON session_worktrees(session_id);

CREATE INDEX idx_telemetry_event_occurred_at
    ON telemetry_event(occurred_at DESC);

CREATE INDEX idx_telemetry_event_name
    ON telemetry_event(name, occurred_at DESC);

CREATE INDEX idx_telemetry_event_project
    ON telemetry_event(project_id, occurred_at DESC);

CREATE INDEX idx_telemetry_event_session
    ON telemetry_event(session_id, occurred_at DESC);

CREATE INDEX idx_review_run_session_batch
    ON review_run (session_id, batch_id, created_at)
    WHERE batch_id != '';

CREATE INDEX idx_pr_reviews_lookup ON pr_reviews (pr_url, submitted_at);

CREATE INDEX idx_shell_terminals_app_run
    ON shell_terminals(app_run_id, created_at);

CREATE INDEX idx_session_cleanup_facts_next_attempt ON session_cleanup_facts (next_attempt_at);

CREATE INDEX idx_notifications_status_history
    ON notifications(status, created_at DESC, id DESC);

CREATE INDEX idx_notifications_history
    ON notifications(created_at DESC, id DESC);

CREATE UNIQUE INDEX idx_notifications_open_dedupe
    ON notifications(session_id, type, pr_url)
    WHERE status = 'unread' OR resolved_at IS NULL;

CREATE INDEX idx_notifications_unresolved
    ON notifications(resolved_at, created_at DESC, id DESC);

CREATE UNIQUE INDEX idx_review_run_session_pr_sha_harness
    ON review_run (session_id, pr_url, target_sha, harness)
    WHERE target_sha != ''
        AND status NOT IN ('failed', 'cancelled')
        AND (status = 'running' OR verdict NOT IN ('', 'changes_requested'));

CREATE UNIQUE INDEX idx_conversations_session ON conversations(session_id)
    WHERE session_id IS NOT NULL;

CREATE UNIQUE INDEX idx_conversations_project_scope ON conversations(project_id)
	WHERE scope = 'project';

CREATE INDEX idx_conversations_current_session ON conversations(current_session_id)
	WHERE current_session_id IS NOT NULL;

CREATE UNIQUE INDEX idx_conversation_messages_provider_item
    ON conversation_messages(conversation_id, provider_item_id)
    WHERE provider_item_id <> '';

CREATE UNIQUE INDEX idx_conversation_messages_client_id
    ON conversation_messages(conversation_id, client_message_id)
    WHERE client_message_id <> '';

CREATE INDEX idx_conversation_messages_order
    ON conversation_messages(conversation_id, sequence);

CREATE UNIQUE INDEX idx_conversation_provider_events_dedupe
    ON conversation_provider_events(conversation_id, provider_event_id)
    WHERE provider_event_id <> '';

CREATE INDEX idx_conversation_provider_events_replay
    ON conversation_provider_events(conversation_id, id);

CREATE UNIQUE INDEX idx_session_interface_transition_active
    ON session_interface_transitions(session_id)
    WHERE phase NOT IN ('completed', 'failed', 'cancelled', 'recovery_required');

CREATE INDEX idx_session_interface_transition_history
    ON session_interface_transitions(session_id, created_at DESC);

CREATE INDEX idx_session_interface_transition_messages_pending
    ON session_interface_transition_messages(transition_id, id)
    WHERE delivered_at IS NULL;

CREATE INDEX idx_conversation_messages_branch
    ON conversation_messages(branch_id, sequence);

CREATE INDEX idx_conversation_provider_events_branch
    ON conversation_provider_events(branch_id, id);

CREATE INDEX idx_pr_reviews_target_sha ON pr_reviews (pr_url, target_sha, submitted_at);

CREATE UNIQUE INDEX idx_pr_provider_identity
    ON pr(provider, host, provider_id)
    WHERE provider_id != '';

CREATE INDEX idx_pr_url_alias_canonical ON pr_url_alias(canonical_url);

CREATE INDEX idx_conversation_branches_lineage
    ON conversation_branches(conversation_id, parent_branch_id, fork_after_sequence);

CREATE INDEX idx_conversation_branches_provider_identity
    ON conversation_branches(conversation_id, provider_conversation_id);

CREATE INDEX idx_change_log_project ON change_log (project_id, seq);

CREATE UNIQUE INDEX idx_conversation_activities_provider_item
    ON conversation_activities(conversation_id, provider_item_id)
    WHERE provider_item_id <> '';

CREATE UNIQUE INDEX idx_conversation_activities_request
    ON conversation_activities(conversation_id, request_id)
    WHERE request_id <> '';

CREATE INDEX idx_conversation_activities_order
    ON conversation_activities(conversation_id, sequence);

CREATE INDEX idx_conversation_activities_pending
    ON conversation_activities(conversation_id, kind, status);

CREATE INDEX idx_conversation_activities_branch
    ON conversation_activities(branch_id, sequence);

CREATE INDEX idx_usage_sources_state_retry ON usage_sources (state, next_retry_at);

CREATE INDEX idx_usage_sources_binding_kind ON usage_sources (binding_id, kind);

CREATE INDEX idx_usage_sources_codex_native_latest
    ON usage_sources (kind, native_session_id, binding_id, generation DESC, id DESC);

CREATE INDEX idx_change_log_created_at_seq ON change_log (created_at, seq);

CREATE UNIQUE INDEX idx_codex_account_switches_one_active
ON codex_account_switches((1))
WHERE phase NOT IN ('completed', 'failed');

CREATE INDEX idx_usage_bindings_session_state ON usage_bindings (session_id, state);

CREATE INDEX idx_model_usage_events_binding_model ON model_usage_events (binding_id, model_id);

CREATE INDEX idx_model_usage_events_usage_source ON model_usage_events (usage_source_id);

CREATE INDEX idx_model_usage_events_cost_candidates
    ON model_usage_events (billing_provider_id, pricing_version, id)
    WHERE estimated_cost_nanos IS NULL;

CREATE INDEX idx_model_usage_events_canonical_cost_candidates
    ON model_usage_events (
        CASE lower(trim(billing_provider_id))
            WHEN 'z.ai' THEN 'zai'
            ELSE lower(trim(billing_provider_id))
        END,
        id
    )
    WHERE billing_provider_id IS NOT NULL
      AND estimated_cost_nanos IS NULL;

CREATE INDEX idx_model_usage_events_open_attribution
    ON model_usage_events (usage_source_id, id)
    WHERE billing_provider_id IS NULL OR billing_provider_source = 'inferred';

CREATE INDEX idx_conversation_turns_conversation
    ON conversation_turns(conversation_id, requested_at);

CREATE UNIQUE INDEX idx_conversation_turns_provider
    ON conversation_turns(conversation_id, provider_turn_id)
    WHERE provider_turn_id <> '';

CREATE INDEX idx_conversation_turns_branch
    ON conversation_turns(branch_id, requested_at);

CREATE INDEX idx_conversation_turns_retry_source
    ON conversation_turns(conversation_id, retry_of_turn_id)
    WHERE retry_of_turn_id IS NOT NULL;

CREATE VIEW usage_codex_source_discovery AS
SELECT source_id, binding_id, native_session_id,
    CASE WHEN child_ids_json IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM json_each(child_ids_json) WHERE type <> 'text'
    ) THEN child_ids_json ELSE '[]' END AS discovered_child_ids_json,
    CASE WHEN child_ids_json IS NOT NULL AND EXISTS (
        SELECT 1 FROM json_each(child_ids_json) WHERE type <> 'text'
    ) THEN 1 ELSE 0 END AS has_mixed_child_types
FROM (
    SELECT id AS source_id, binding_id, native_session_id,
        CASE WHEN json_valid(parser_state_json)
          AND json_type(parser_state_json, '$') = 'object'
          AND json_type(parser_state_json, '$.version') = 'integer'
          AND json_extract(parser_state_json, '$.version') = 1
          AND json_type(parser_state_json, '$.source_kind') = 'text'
          AND json_extract(parser_state_json, '$.source_kind') = 'codex_rollout'
          AND json_type(parser_state_json, '$.codex') = 'object'
          AND json_type(parser_state_json, '$.codex.discovered_child_ids') = 'array'
        THEN json_extract(parser_state_json, '$.codex.discovered_child_ids') END AS child_ids_json
    FROM usage_sources WHERE kind = 'codex_rollout'
);

CREATE VIEW usage_codex_pending_children AS
SELECT spawning.binding_id, CAST(discovered.value AS TEXT) AS native_session_id
FROM usage_codex_source_discovery spawning
JOIN json_each(spawning.discovered_child_ids_json) discovered
WHERE discovered.type = 'text'
  AND length(discovered.value) = 36
  AND substr(discovered.value, 9, 1) = '-'
  AND substr(discovered.value, 14, 1) = '-'
  AND substr(discovered.value, 19, 1) = '-'
  AND substr(discovered.value, 24, 1) = '-'
  AND lower(discovered.value) = discovered.value
  AND length(replace(discovered.value, '-', '')) = 32
  AND replace(discovered.value, '-', '') NOT GLOB '*[^0-9a-f]*'
  AND spawning.source_id = (
      SELECT latest.id FROM usage_sources latest
      WHERE latest.binding_id = spawning.binding_id
        AND latest.kind = 'codex_rollout'
        AND latest.native_session_id = spawning.native_session_id
      ORDER BY latest.generation DESC, latest.id DESC LIMIT 1
  )
  AND NOT EXISTS (
      SELECT 1 FROM usage_sources registered
      WHERE registered.binding_id = spawning.binding_id
        AND registered.kind = 'codex_rollout'
        AND registered.native_session_id = CAST(discovered.value AS TEXT)
  );

CREATE VIEW usage_session_integrity AS
SELECT ub.session_id,
    CAST(MAX(CASE
        WHEN ub.state = 'partial'
          OR ub.last_error_code NOT IN ('', 'source_discovery_pending', 'artifact_missing', 'source_read_failed')
          OR (us.last_error_code <> 'artifact_replaced' AND (
              us.anomaly_count > 0
              OR us.last_error_code NOT IN ('', 'source_discovery_pending', 'artifact_missing', 'source_read_failed')
          ))
        THEN 1 ELSE 0
    END) AS INTEGER) AS incomplete
FROM usage_bindings ub
LEFT JOIN usage_sources us ON us.binding_id = ub.id
GROUP BY ub.session_id;

CREATE TRIGGER conversation_messages_branch_insert
AFTER INSERT ON conversation_messages
WHEN NEW.branch_id = ''
BEGIN
    UPDATE conversation_messages
    SET branch_id = (SELECT active_branch_id FROM conversations WHERE id = NEW.conversation_id)
    WHERE id = NEW.id;
END;

CREATE TRIGGER conversation_provider_events_branch_insert
AFTER INSERT ON conversation_provider_events
WHEN NEW.branch_id = ''
BEGIN
    UPDATE conversation_provider_events
    SET branch_id = (SELECT active_branch_id FROM conversations WHERE id = NEW.conversation_id)
    WHERE id = NEW.id;
END;

CREATE TRIGGER conversation_branch_root_provider_update
AFTER UPDATE OF provider_conversation_id ON sessions
WHEN OLD.provider_conversation_id = '' AND NEW.provider_conversation_id <> ''
BEGIN
    UPDATE conversation_branches
    SET provider_conversation_id = NEW.provider_conversation_id
    WHERE parent_branch_id IS NULL
      AND provider_conversation_id = ''
      AND id IN (
          SELECT active_branch_id
          FROM conversations
          WHERE current_session_id = NEW.id
      );
END;

CREATE TRIGGER conversation_messages_cdc_insert
AFTER INSERT ON conversation_messages
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id, 'conversationId', NEW.conversation_id,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           NEW.updated_at
    FROM conversations c
    JOIN sessions s ON s.id = c.current_session_id
    WHERE c.id = NEW.conversation_id;
END;

CREATE TRIGGER conversation_messages_cdc_update
AFTER UPDATE ON conversation_messages
WHEN OLD.revision <> NEW.revision
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id, 'conversationId', c.id,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           NEW.updated_at
    FROM conversations c
    JOIN sessions s ON s.id = c.current_session_id
    WHERE c.id = NEW.conversation_id;
END;

CREATE TRIGGER pr_cdc_insert
AFTER INSERT ON pr
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id), NEW.session_id, 'pr_created',
        json_object('url', NEW.url, 'session', NEW.session_id, 'state', NEW.pr_state,
                    'ci', NEW.ci_state, 'review', NEW.review_decision, 'mergeability', NEW.mergeability),
        NEW.updated_at);
END;

CREATE TRIGGER pr_checks_cdc_insert
AFTER INSERT ON pr_checks
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT s.project_id FROM pr p JOIN sessions s ON s.id = p.session_id WHERE p.url = NEW.pr_url),
        (SELECT session_id FROM pr WHERE url = NEW.pr_url),
        'pr_check_recorded',
        json_object('pr', NEW.pr_url, 'name', NEW.name, 'commit', NEW.commit_hash, 'status', NEW.status),
        NEW.created_at);
END;

CREATE TRIGGER pr_checks_cdc_update
AFTER UPDATE ON pr_checks
WHEN OLD.status <> NEW.status
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT s.project_id FROM pr p JOIN sessions s ON s.id = p.session_id WHERE p.url = NEW.pr_url),
        (SELECT session_id FROM pr WHERE url = NEW.pr_url),
        'pr_check_recorded',
        json_object('pr', NEW.pr_url, 'name', NEW.name, 'commit', NEW.commit_hash, 'status', NEW.status),
        datetime('now'));
END;

CREATE TRIGGER pr_review_threads_cdc_insert
AFTER INSERT ON pr_review_threads
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT s.project_id FROM pr p JOIN sessions s ON s.id = p.session_id WHERE p.url = NEW.pr_url),
        (SELECT session_id FROM pr WHERE url = NEW.pr_url),
        'pr_review_thread_added',
        json_object(
            'pr', NEW.pr_url,
            'thread', NEW.thread_id,
            'path', NEW.path,
            'line', NEW.line,
            'resolved', json(CASE WHEN NEW.resolved THEN 'true' ELSE 'false' END),
            'isBot', json(CASE WHEN NEW.is_bot THEN 'true' ELSE 'false' END)
        ),
        NEW.updated_at);
END;

CREATE TRIGGER pr_review_threads_cdc_update
AFTER UPDATE ON pr_review_threads
WHEN OLD.resolved <> NEW.resolved
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT s.project_id FROM pr p JOIN sessions s ON s.id = p.session_id WHERE p.url = NEW.pr_url),
        (SELECT session_id FROM pr WHERE url = NEW.pr_url),
        'pr_review_thread_resolved',
        json_object(
            'pr', NEW.pr_url,
            'thread', NEW.thread_id,
            'path', NEW.path,
            'line', NEW.line,
            'resolved', json(CASE WHEN NEW.resolved THEN 'true' ELSE 'false' END)
        ),
        NEW.updated_at);
END;

CREATE TRIGGER pr_session_cdc_update
AFTER UPDATE ON pr
WHEN OLD.session_id <> NEW.session_id
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT project_id FROM sessions WHERE id = NEW.session_id),
        NEW.session_id,
        'pr_session_changed',
        json_object(
            'url', NEW.url,
            'fromSession', OLD.session_id,
            'toSession', NEW.session_id),
        NEW.updated_at);
END;

CREATE TRIGGER session_cleanup_facts_cdc_insert
AFTER INSERT ON session_cleanup_facts
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id), NEW.session_id, 'session_updated',
        json_object('id', NEW.session_id),
        datetime('now'));
END;

CREATE TRIGGER session_cleanup_facts_cdc_update
AFTER UPDATE ON session_cleanup_facts
WHEN OLD.workspace_disposition <> NEW.workspace_disposition
    OR (OLD.runtime_released_at IS NULL) <> (NEW.runtime_released_at IS NULL)
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id), NEW.session_id, 'session_updated',
        json_object('id', NEW.session_id),
        datetime('now'));
END;

CREATE TRIGGER session_interface_transitions_cdc_insert
AFTER INSERT ON session_interface_transitions
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id,
                       'interfaceTransitionId', NEW.id,
                       'interfaceTransitionPhase', NEW.phase,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           NEW.updated_at
    FROM sessions s WHERE s.id = NEW.session_id;
END;

CREATE TRIGGER session_interface_transitions_cdc_update
AFTER UPDATE ON session_interface_transitions
WHEN OLD.phase <> NEW.phase
    OR OLD.error_code <> NEW.error_code
    OR OLD.error_detail <> NEW.error_detail
    OR OLD.notice_acknowledged_at IS NOT NEW.notice_acknowledged_at
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id,
                       'interfaceTransitionId', NEW.id,
                       'interfaceTransitionPhase', NEW.phase,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           COALESCE(NEW.notice_acknowledged_at, NEW.updated_at)
    FROM sessions s WHERE s.id = NEW.session_id;
END;

CREATE TRIGGER sessions_cdc_insert
AFTER INSERT ON sessions
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (NEW.project_id, NEW.id, 'session_created',
        json_object('id', NEW.id, 'activity', NEW.activity_state, 'isTerminated', json(CASE WHEN NEW.is_terminated THEN 'true' ELSE 'false' END)),
        NEW.updated_at);
END;

CREATE TRIGGER review_run_cdc_insert
AFTER INSERT ON review_run
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT project_id FROM sessions WHERE id = NEW.session_id),
        NEW.session_id,
        'review_run_created',
        json_object(
            'id', NEW.id,
            'reviewId', NEW.review_id,
            'sessionId', NEW.session_id,
            'pr', NEW.pr_url,
            'targetSha', NEW.target_sha,
            'status', NEW.status,
            'verdict', NEW.verdict,
            'triggerSource', NEW.trigger_source,
            'githubReviewId', NEW.github_review_id,
            'autoInjectReview', json(CASE WHEN NEW.auto_inject_review THEN 'true' ELSE 'false' END)
        ),
        NEW.created_at);
END;

CREATE TRIGGER review_run_cdc_update
AFTER UPDATE ON review_run
WHEN OLD.status <> NEW.status
    OR OLD.verdict <> NEW.verdict
    OR OLD.body <> NEW.body
    OR OLD.github_review_id <> NEW.github_review_id
    OR OLD.auto_inject_review <> NEW.auto_inject_review
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (
        (SELECT project_id FROM sessions WHERE id = NEW.session_id),
        NEW.session_id,
        'review_run_updated',
        json_object(
            'id', NEW.id,
            'reviewId', NEW.review_id,
            'sessionId', NEW.session_id,
            'pr', NEW.pr_url,
            'targetSha', NEW.target_sha,
            'status', NEW.status,
            'verdict', NEW.verdict,
            'triggerSource', NEW.trigger_source,
            'githubReviewId', NEW.github_review_id,
            'autoInjectReview', json(CASE WHEN NEW.auto_inject_review THEN 'true' ELSE 'false' END)
        ),
        datetime('now'));
END;

CREATE TRIGGER conversation_activities_branch_insert
AFTER INSERT ON conversation_activities
WHEN NEW.branch_id = ''
BEGIN
    UPDATE conversation_activities
    SET branch_id = (SELECT active_branch_id FROM conversations WHERE id = NEW.conversation_id)
    WHERE id = NEW.id;
END;

CREATE TRIGGER conversation_activities_cdc_insert
AFTER INSERT ON conversation_activities
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id, 'conversationId', c.id,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           NEW.updated_at
    FROM conversations c
    JOIN sessions s ON s.id = c.current_session_id
    WHERE c.id = NEW.conversation_id;
END;

CREATE TRIGGER conversation_activities_cdc_update
AFTER UPDATE ON conversation_activities
WHEN OLD.revision <> NEW.revision
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id, 'conversationId', c.id,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           NEW.updated_at
    FROM conversations c
    JOIN sessions s ON s.id = c.current_session_id
    WHERE c.id = NEW.conversation_id;
END;

CREATE TRIGGER pr_cdc_update
AFTER UPDATE ON pr
WHEN OLD.pr_state <> NEW.pr_state
    OR OLD.ci_state <> NEW.ci_state
    OR OLD.review_decision <> NEW.review_decision
    OR OLD.mergeability <> NEW.mergeability
    OR OLD.auto_inject_ci <> NEW.auto_inject_ci
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id), NEW.session_id, 'pr_updated',
        json_object('url', NEW.url, 'session', NEW.session_id, 'state', NEW.pr_state,
                    'ci', NEW.ci_state, 'review', NEW.review_decision, 'mergeability', NEW.mergeability,
                    'autoInjectCI', json(CASE WHEN NEW.auto_inject_ci THEN 'true' ELSE 'false' END)),
        NEW.updated_at);
END;

CREATE TRIGGER usage_sources_cdc_update AFTER UPDATE ON usage_sources
WHEN OLD.anomaly_count IS NOT NEW.anomaly_count
  OR OLD.last_error_code IS NOT NEW.last_error_code
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, ub.session_id, 'session_updated', json_object('id', ub.session_id), NEW.updated_at
    FROM usage_bindings ub JOIN sessions s ON s.id = ub.session_id WHERE ub.id = NEW.binding_id;
END;

CREATE TRIGGER usage_bindings_cdc_insert AFTER INSERT ON usage_bindings BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id),
            NEW.session_id, 'session_updated', json_object('id', NEW.session_id), NEW.updated_at);
END;

CREATE TRIGGER usage_bindings_cdc_update AFTER UPDATE ON usage_bindings BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES ((SELECT project_id FROM sessions WHERE id = NEW.session_id),
            NEW.session_id, 'session_updated', json_object('id', NEW.session_id), NEW.updated_at);
END;

CREATE TRIGGER sessions_cdc_update
AFTER UPDATE ON sessions
WHEN OLD.activity_state <> NEW.activity_state
    OR OLD.is_terminated <> NEW.is_terminated
    OR (OLD.first_signal_at IS NULL AND NEW.first_signal_at IS NOT NULL)
    OR OLD.preview_url <> NEW.preview_url
    OR OLD.preview_revision <> NEW.preview_revision
    OR OLD.display_name <> NEW.display_name
    OR OLD.terminate_on_pr_merge <> NEW.terminate_on_pr_merge
    OR OLD.is_pinned <> NEW.is_pinned
    OR OLD.pinned_at <> NEW.pinned_at
    OR (OLD.pinned_at IS NULL AND NEW.pinned_at IS NOT NULL)
    OR (OLD.pinned_at IS NOT NULL AND NEW.pinned_at IS NULL)
    OR OLD.session_mode <> NEW.session_mode
    OR OLD.auto_inject_review <> NEW.auto_inject_review
    OR OLD.auto_review_enabled <> NEW.auto_review_enabled
    OR OLD.harness <> NEW.harness
    OR OLD.runtime_launch_id <> NEW.runtime_launch_id
    OR OLD.agent_session_id <> NEW.agent_session_id
    OR OLD.native_transcript_path <> NEW.native_transcript_path
    OR OLD.auto_inject_ci <> NEW.auto_inject_ci
    OR OLD.latest_user_prompt_at IS NOT NEW.latest_user_prompt_at
    OR OLD.workflow_mode <> NEW.workflow_mode
    OR OLD.review_locked <> NEW.review_locked
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (NEW.project_id, NEW.id, 'session_updated',
        json_object(
            'id', NEW.id,
            'activity', NEW.activity_state,
            'isTerminated', json(CASE WHEN NEW.is_terminated THEN 'true' ELSE 'false' END),
            'terminateOnPrMerge', json(CASE WHEN NEW.terminate_on_pr_merge THEN 'true' ELSE 'false' END),
            'previewUrl', NEW.preview_url,
            'previewRevision', NEW.preview_revision,
            'isPinned', json(CASE WHEN NEW.is_pinned THEN 'true' ELSE 'false' END),
            'mode', NEW.session_mode,
            'autoInjectReview', json(CASE WHEN NEW.auto_inject_review THEN 'true' ELSE 'false' END),
            'autoInjectCI', json(CASE WHEN NEW.auto_inject_ci THEN 'true' ELSE 'false' END),
            'autoReviewEnabled', json(CASE WHEN NEW.auto_review_enabled THEN 'true' ELSE 'false' END),
            'workflowMode', NEW.workflow_mode,
            'reviewLocked', json(CASE WHEN NEW.review_locked THEN 'true' ELSE 'false' END)
        ),
        NEW.updated_at);
END;

CREATE TRIGGER sessions_revision_update
AFTER UPDATE ON sessions
WHEN NEW.revision = OLD.revision
BEGIN
    UPDATE sessions SET revision = OLD.revision + 1 WHERE id = NEW.id;
END;

CREATE TRIGGER sessions_cdc_delete
AFTER DELETE ON sessions
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    VALUES (OLD.project_id, NULL, 'session_updated',
        json_object('id', OLD.id, 'sessionId', OLD.id, 'retired', json('true'),
                    'kind', COALESCE(OLD.kind, 'worker'), 'num', OLD.num),
        datetime('now'));
END;

CREATE TRIGGER conversation_turns_branch_insert
AFTER INSERT ON conversation_turns
WHEN NEW.branch_id = ''
BEGIN
    UPDATE conversation_turns
    SET branch_id = (SELECT active_branch_id FROM conversations WHERE id = NEW.conversation_id)
    WHERE id = NEW.id;
END;

CREATE TRIGGER conversation_turns_cdc_update
AFTER UPDATE ON conversation_turns
WHEN OLD.state <> NEW.state
BEGIN
    INSERT INTO change_log (project_id, session_id, event_type, payload, created_at)
    SELECT s.project_id, s.id, 'session_updated',
           json_object('id', s.id, 'sessionId', s.id, 'conversationId', NEW.conversation_id,
                       'activity', s.activity_state,
                       'isTerminated', json(CASE WHEN s.is_terminated THEN 'true' ELSE 'false' END)),
           COALESCE(NEW.completed_at, NEW.started_at, NEW.requested_at)
    FROM sessions s
    WHERE s.id = NEW.handled_by_session_id;
END;

-- +goose StatementEnd

-- +goose Down

-- +goose StatementBegin



-- Drops every object the baseline creates, in reverse creation order.

-- The pre-baseline chain was never reversible either: its Down sections

-- could not undo renumbered or burned versions, so goose down was already

-- best-effort. This at least leaves an empty schema rather than a partial one.



DROP TRIGGER IF EXISTS conversation_messages_branch_insert;

DROP TRIGGER IF EXISTS conversation_provider_events_branch_insert;

DROP TRIGGER IF EXISTS conversation_branch_root_provider_update;

DROP TRIGGER IF EXISTS conversation_messages_cdc_insert;

DROP TRIGGER IF EXISTS conversation_messages_cdc_update;

DROP TRIGGER IF EXISTS pr_cdc_insert;

DROP TRIGGER IF EXISTS pr_checks_cdc_insert;

DROP TRIGGER IF EXISTS pr_checks_cdc_update;

DROP TRIGGER IF EXISTS pr_review_threads_cdc_insert;

DROP TRIGGER IF EXISTS pr_review_threads_cdc_update;

DROP TRIGGER IF EXISTS pr_session_cdc_update;

DROP TRIGGER IF EXISTS session_cleanup_facts_cdc_insert;

DROP TRIGGER IF EXISTS session_cleanup_facts_cdc_update;

DROP TRIGGER IF EXISTS session_interface_transitions_cdc_insert;

DROP TRIGGER IF EXISTS session_interface_transitions_cdc_update;

DROP TRIGGER IF EXISTS sessions_cdc_insert;

DROP TRIGGER IF EXISTS review_run_cdc_insert;

DROP TRIGGER IF EXISTS review_run_cdc_update;

DROP TRIGGER IF EXISTS conversation_activities_branch_insert;

DROP TRIGGER IF EXISTS conversation_activities_cdc_insert;

DROP TRIGGER IF EXISTS conversation_activities_cdc_update;

DROP TRIGGER IF EXISTS pr_cdc_update;

DROP TRIGGER IF EXISTS usage_sources_cdc_update;

DROP TRIGGER IF EXISTS usage_bindings_cdc_insert;

DROP TRIGGER IF EXISTS usage_bindings_cdc_update;

DROP TRIGGER IF EXISTS sessions_cdc_update;

DROP TRIGGER IF EXISTS sessions_revision_update;

DROP TRIGGER IF EXISTS sessions_cdc_delete;

DROP TRIGGER IF EXISTS conversation_turns_branch_insert;

DROP TRIGGER IF EXISTS conversation_turns_cdc_update;

DROP VIEW IF EXISTS usage_codex_source_discovery;

DROP VIEW IF EXISTS usage_codex_pending_children;

DROP VIEW IF EXISTS usage_session_integrity;

DROP INDEX IF EXISTS idx_sessions_project;

DROP INDEX IF EXISTS idx_pr_session;

DROP INDEX IF EXISTS idx_pr_checks_lookup;

DROP INDEX IF EXISTS idx_pr_review_threads_lookup;

DROP INDEX IF EXISTS idx_session_worktrees_session;

DROP INDEX IF EXISTS idx_telemetry_event_occurred_at;

DROP INDEX IF EXISTS idx_telemetry_event_name;

DROP INDEX IF EXISTS idx_telemetry_event_project;

DROP INDEX IF EXISTS idx_telemetry_event_session;

DROP INDEX IF EXISTS idx_review_run_session_batch;

DROP INDEX IF EXISTS idx_pr_reviews_lookup;

DROP INDEX IF EXISTS idx_shell_terminals_app_run;

DROP INDEX IF EXISTS idx_session_cleanup_facts_next_attempt;

DROP INDEX IF EXISTS idx_notifications_status_history;

DROP INDEX IF EXISTS idx_notifications_history;

DROP INDEX IF EXISTS idx_notifications_open_dedupe;

DROP INDEX IF EXISTS idx_notifications_unresolved;

DROP INDEX IF EXISTS idx_review_run_session_pr_sha_harness;

DROP INDEX IF EXISTS idx_conversations_session;

DROP INDEX IF EXISTS idx_conversations_project_scope;

DROP INDEX IF EXISTS idx_conversations_current_session;

DROP INDEX IF EXISTS idx_conversation_messages_provider_item;

DROP INDEX IF EXISTS idx_conversation_messages_client_id;

DROP INDEX IF EXISTS idx_conversation_messages_order;

DROP INDEX IF EXISTS idx_conversation_provider_events_dedupe;

DROP INDEX IF EXISTS idx_conversation_provider_events_replay;

DROP INDEX IF EXISTS idx_session_interface_transition_active;

DROP INDEX IF EXISTS idx_session_interface_transition_history;

DROP INDEX IF EXISTS idx_session_interface_transition_messages_pending;

DROP INDEX IF EXISTS idx_conversation_messages_branch;

DROP INDEX IF EXISTS idx_conversation_provider_events_branch;

DROP INDEX IF EXISTS idx_pr_reviews_target_sha;

DROP INDEX IF EXISTS idx_pr_provider_identity;

DROP INDEX IF EXISTS idx_pr_url_alias_canonical;

DROP INDEX IF EXISTS idx_conversation_branches_lineage;

DROP INDEX IF EXISTS idx_conversation_branches_provider_identity;

DROP INDEX IF EXISTS idx_change_log_project;

DROP INDEX IF EXISTS idx_conversation_activities_provider_item;

DROP INDEX IF EXISTS idx_conversation_activities_request;

DROP INDEX IF EXISTS idx_conversation_activities_order;

DROP INDEX IF EXISTS idx_conversation_activities_pending;

DROP INDEX IF EXISTS idx_conversation_activities_branch;

DROP INDEX IF EXISTS idx_usage_sources_state_retry;

DROP INDEX IF EXISTS idx_usage_sources_binding_kind;

DROP INDEX IF EXISTS idx_usage_sources_codex_native_latest;

DROP INDEX IF EXISTS idx_change_log_created_at_seq;

DROP INDEX IF EXISTS idx_codex_account_switches_one_active;

DROP INDEX IF EXISTS idx_usage_bindings_session_state;

DROP INDEX IF EXISTS idx_model_usage_events_binding_model;

DROP INDEX IF EXISTS idx_model_usage_events_usage_source;

DROP INDEX IF EXISTS idx_model_usage_events_cost_candidates;

DROP INDEX IF EXISTS idx_model_usage_events_canonical_cost_candidates;

DROP INDEX IF EXISTS idx_model_usage_events_open_attribution;

DROP INDEX IF EXISTS idx_conversation_turns_conversation;

DROP INDEX IF EXISTS idx_conversation_turns_provider;

DROP INDEX IF EXISTS idx_conversation_turns_branch;

DROP INDEX IF EXISTS idx_conversation_turns_retry_source;

DROP TABLE IF EXISTS telemetry_event;

DROP TABLE IF EXISTS projects;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS pr;

DROP TABLE IF EXISTS pr_checks;

DROP TABLE IF EXISTS pr_comment;

DROP TABLE IF EXISTS pr_review_threads;

DROP TABLE IF EXISTS workspace_repos;

DROP TABLE IF EXISTS session_worktrees;

DROP TABLE IF EXISTS notifications;

DROP TABLE IF EXISTS pr_reviews;

DROP TABLE IF EXISTS shell_terminals;

DROP TABLE IF EXISTS session_cleanup_facts;

DROP TABLE IF EXISTS agent_model_catalog;

DROP TABLE IF EXISTS conversations;

DROP TABLE IF EXISTS conversation_provider_events;

DROP TABLE IF EXISTS app_settings;

DROP TABLE IF EXISTS session_interface_transitions;

DROP TABLE IF EXISTS session_interface_transition_messages;

DROP TABLE IF EXISTS review;

DROP TABLE IF EXISTS review_run;

DROP TABLE IF EXISTS pr_url_alias;

DROP TABLE IF EXISTS change_log;

DROP TABLE IF EXISTS agent_install_jobs;

DROP TABLE IF EXISTS conversation_queued_edit_deliveries;

DROP TABLE IF EXISTS conversation_edit_deliveries;

DROP TABLE IF EXISTS conversation_steer_deliveries;

DROP TABLE IF EXISTS codex_account_switches;

DROP TABLE IF EXISTS usage_bindings;

DROP TABLE IF EXISTS usage_sources;

DROP TABLE IF EXISTS model_usage_events;

DROP TABLE IF EXISTS retired_session_nums;

DROP TABLE IF EXISTS conversation_turns;

DROP TABLE IF EXISTS conversation_messages;

DROP TABLE IF EXISTS conversation_branches;

DROP TABLE IF EXISTS conversation_activities;

-- +goose StatementEnd
